drop table if exists PUBLIC.SHIPPING_INFO;
drop table if exists PUBLIC.SHIPPING_STATUS;
drop table if exists PUBLIC.SHIPPING_COUNTRY_RATES;
drop table if exists PUBLIC.SHIPPING_AGREEMENT;

CREATE TABLE PUBLIC.SHIPPING_COUNTRY_RATES (
    SHIPPING_COUNTRY_ID SERIAL PRIMARY KEY,
    SHIPPING_COUNTRY TEXT NULL,
    SHIPPING_COUNTRY_BASE_RATE NUMERIC(14, 3) NULL
);

CREATE TABLE PUBLIC.SHIPPING_AGREEMENT (
    AGREEMENT_ID BIGINT PRIMARY KEY,
    AGREEMENT_NUMBER TEXT,
    AGREEMENT_RATE NUMERIC(14, 3),
    AGREEMENT_COMMISSION NUMERIC(14, 3) 
);
drop table if exists PUBLIC.SHIPPING_TRANSFER;
CREATE TABLE PUBLIC.SHIPPING_TRANSFER (
    TRANSFER_TYPE_ID SERIAL PRIMARY KEY,
    TRANSFER_TYPE TEXT,
    TRANSFER_MODEL TEXT,
    SHIPPING_TRANSFER_RATE NUMERIC(14, 3) 
);

CREATE TABLE PUBLIC.SHIPPING_INFO (
    SHIPPING_ID INT8 PRIMARY KEY,
    VENDOR_ID INT8 NULL,
    PAYMENT_AMOUNT NUMERIC(14, 2) NULL, 
    SHIPPING_PLAN_DATETIME TIMESTAMP NULL, 
    TRANSFER_TYPE_ID INT8 REFERENCES PUBLIC.SHIPPING_TRANSFER (TRANSFER_TYPE_ID) ON UPDATE CASCADE,
    SHIPPING_COUNTRY_ID INT8 REFERENCES PUBLIC.SHIPPING_COUNTRY_RATES (SHIPPING_COUNTRY_ID) ON UPDATE CASCADE,
    AGREEMENT_ID INT8 REFERENCES PUBLIC.SHIPPING_AGREEMENT (AGREEMENT_ID) ON UPDATE CASCADE
);

CREATE TABLE PUBLIC.SHIPPING_STATUS (
    SHIPPING_ID INT8 PRIMARY KEY,
    STATUS TEXT NULL,
    STATE TEXT NULL,
    SHIPPING_START_FACT_DATETIME TIMESTAMP NULL,
    SHIPPING_END_FACT_DATETIME TIMESTAMP NULL
);