INSERT INTO PUBLIC.SHIPPING_COUNTRY_RATES
(SHIPPING_COUNTRY, SHIPPING_COUNTRY_BASE_RATE)
SELECT
    DISTINCT SHIPPING_COUNTRY,
    SHIPPING_COUNTRY_BASE_RATE
FROM PUBLIC.SHIPPING;


INSERT INTO PUBLIC.SHIPPING_AGREEMENT 
SELECT 
     DISTINCT CAST((REGEXP_SPLIT_TO_ARRAY(VENDOR_AGREEMENT_DESCRIPTION, E'\\:+'))[1] AS BIGINT) AS AGREEMENTID,
     (REGEXP_SPLIT_TO_ARRAY(VENDOR_AGREEMENT_DESCRIPTION, E'\\:+'))[2] AS AGREEMENT_NUMBER,
     CAST((REGEXP_SPLIT_TO_ARRAY(VENDOR_AGREEMENT_DESCRIPTION, E'\\:+'))[3] AS NUMERIC(14, 3)) AS AGREEMENT_RATE,
     CAST((REGEXP_SPLIT_TO_ARRAY(VENDOR_AGREEMENT_DESCRIPTION, E'\\:+'))[4] AS NUMERIC(14, 3)) AS AGREEMENT_COMMISSION
FROM PUBLIC.SHIPPING;

       
INSERT INTO PUBLIC.SHIPPING_TRANSFER
(TRANSFER_TYPE, TRANSFER_MODEL, SHIPPING_TRANSFER_RATE)
SELECT 
    DISTINCT (REGEXP_SPLIT_TO_ARRAY(SHIPPING_TRANSFER_DESCRIPTION, E'\\:+'))[1] AS TRANSFER_TYPE,
    (REGEXP_SPLIT_TO_ARRAY(SHIPPING_TRANSFER_DESCRIPTION, E'\\:+'))[2] AS TRANSFER_MODEL,
    SHIPPING_TRANSFER_RATE
FROM PUBLIC.SHIPPING;
       

INSERT INTO PUBLIC.SHIPPING_INFO
SELECT
    DISTINCT S.SHIPPING_ID, 
    S.VENDOR_ID, 
    S.PAYMENT_AMOUNT, 
    S.SHIPPING_PLAN_DATETIME,
    T.TRANSFER_TYPE_ID,
    R.SHIPPING_COUNTRY_ID,
    A.AGREEMENT_ID
FROM PUBLIC.SHIPPING S
JOIN PUBLIC.SHIPPING_TRANSFER T 
    ON (REGEXP_SPLIT_TO_ARRAY(S.SHIPPING_TRANSFER_DESCRIPTION, E'\\:+'))[1] = T.TRANSFER_TYPE 
    AND (REGEXP_SPLIT_TO_ARRAY(S.SHIPPING_TRANSFER_DESCRIPTION, E'\\:+'))[2] = TRANSFER_MODEL
JOIN PUBLIC.SHIPPING_COUNTRY_RATES R 
    ON S.SHIPPING_COUNTRY = R.SHIPPING_COUNTRY
JOIN PUBLIC.SHIPPING_AGREEMENT A 
    ON CAST((REGEXP_SPLIT_TO_ARRAY(S.VENDOR_AGREEMENT_DESCRIPTION, E'\\:+'))[1] AS BIGINT) = A.AGREEMENT_ID 
;


INSERT INTO PUBLIC.SHIPPING_STATUS
WITH MAX_STATE_TIME AS
(
    SELECT A.* FROM
        (SELECT 
             SHIPPING_ID, 
             STATUS,
             STATE,
             ROW_NUMBER() OVER(PARTITION BY SHIPPING_ID ORDER BY STATE_DATETIME  DESC) AS RN
         FROM SHIPPING) A WHERE A.RN = 1   
)
SELECT
    M.SHIPPING_ID, 
    M.STATUS,
    M.STATE,
    S.SHIPPING_START_FACT_DATETIME,
    S.SHIPPING_END_FACT_DATETIME
FROM MAX_STATE_TIME M
LEFT JOIN (
        SELECT
            SHIPPING_ID,
            MAX(CASE WHEN STATE = 'booked' THEN STATE_DATETIME END) AS SHIPPING_START_FACT_DATETIME,
            MAX(CASE WHEN STATE = 'recieved' THEN STATE_DATETIME END) AS SHIPPING_END_FACT_DATETIME
        FROM PUBLIC.SHIPPING
        GROUP BY 1
          ) S ON M.SHIPPING_ID = S.SHIPPING_ID
;
